.PHONY: default clean build run lib getwindowlib getmaclib package-linux package-windows package-mac package

project_name = name

default: build run

buildclean:
	rm -f $(project_name).love

clean:
	rm -f $(project_name).love
	rm -rf pkg
	rm -rf lib
	rm -rf temp

build: buildclean
	@./script/build.sh $(project_name)

run:
	@love $(project_name).love

setup:
	git submodule update --init --recursive

package-linux: build
	@./script/package.sh linux

package-windows: build
	@./script/package.sh windows

package-mac: build
	@./script/package.sh osx

subupdate:
	git submodule foreach git pull origin master

package: build package-linux package-windows package-mac
